server/config/routes.rb
Busykoala::Application.routes.draw do
  resources :actions, :only => :create do
    collection do
      get :pattern
    end
  end
  resources :devices, :only => [ :index, :update ]
  root to: 'pages#index'
end

server/app/models/action.rb
class Action
  STORAGE = "#{Rails.root}/tmp/actions.json"

  def self.all
    JSON.parse(File.read(STORAGE)) rescue []
  end

  def self.append(action)
    actions = all
    actions << action

    File.write(STORAGE, actions.to_json)
  end

  def self.clear!
    File.write(STORAGE, '[]')
  end
end

server/app/models/device.rb
class Device
  STORAGE = "#{Rails.root}/tmp/devices.json"

  MAPPING = [
    "BLANK",
    "LAMP",
    "SWITCHER",
    "FAN",
    "TEMPERATURE",
    "SCROLLBAR",
    "BEEPER",
    "PATTERN",
  ]

  BIT_TARGET_INDEXES = [ 1, 6 ]
  VAL_TARGET_INDEXES = [ 3, 7 ]

  def self.all
    JSON.parse(File.read(STORAGE)) rescue []
  end

  def self.find(id)
    all.select{ |device| device["uuid"] == id }.first
  end

  def self.update_all(devices)
    File.write(STORAGE, devices.to_json)
  end
end

server/app/models/relationship.rb
class Relationship
  STORAGE = "#{Rails.root}/tmp/relationship.json"

  def self.all
    JSON.parse(File.read(STORAGE)) rescue {}
  end

  def self.update(relationships)
    File.write(STORAGE, relationships.to_json)
  end
end

server/app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  def create
    if params[:items]
      params[:items].each_pair do |id, value|
        Action.append({
          :id    => id,
          :value => value.to_i
        })
      end
    elsif params[:item]
      Action.append(params[:item])
    else
    end

    if params[:relationships]
      Relationship.update(params[:relationships])
    end

    redirect_to devices_path
  end

  def pattern
    pattern = params[:pattern].to_i

    if pattern == 0
      5.times do |i|
        Action.append({
          :id    => "14:665247461d1c11e395bc73bf3a254a5f:target:#{i+1}",
          :value => 0
        })
      end
    else
      Action.append({
        :id    => "14:665247461d1c11e395bc73bf3a254a5f:target:5",
        :value => params[:pattern].to_i
      })
    end


    render :json => params.to_json, :callback => params[:callback]
  end
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

server/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @devices = Device.all
    respond_to do |format|
      format.html
      format.json { render :json => @devices }
    end
  end
end

server/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/views/devices/index.html.haml
= form_tag actions_path, :method => :post do
  %ul.devices
    - @devices.each do |d|
      - address, uuid, role, index = d["id"].split(":")

      %li.device
        %h3= Device::MAPPING[d["type"]]
        %p
          - if [1, 2].include? d["type"]
            Status: #{d["value"] == 0 ? "OFF" : "ON"}
          - else
            - if d["type"] == 4
              Status: #{d["value"] / 16.0 }
            - else d["type"] == 4
              Status: #{d["value"]}

        - if Device::BIT_TARGET_INDEXES.include? d["type"]
          %p
            %label
              OFF
              %input{ :type => 'radio', :name => "items[#{d['id']}]", :value => 0, :checked => d['value'] == 0 }
            %label
              ON
              %input{ :type => 'radio', :name => "items[#{d['id']}]", :value => 1, :checked => d['value'] != 0 }

        - elsif Device::VAL_TARGET_INDEXES.include? d["type"]
          %p
            %label
              Num
              %input{ :type => 'range', :name => "items[#{d['id']}]", :value => d['value'] }


        - if role == "source"
          %p
            %label
              Targets
              %select{ :name => "relationships[#{d['id']}]" }
                %option NOTHING
                - @devices.each do |d2|
                  - if d2["id"].split(":")[2] == 'target'
                    %option{ :value => d2['id'] }= Device::MAPPING[d2["type"]]

  %input{ :type => :submit }

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type", content="text/html; charset=utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>BusyKoala</title>
  <meta name="description" content="BusyKoala">
  <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
  <%= stylesheet_link_tag "font" %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>